### ISSUE TITLE
Crash without Too Many Glyphs

### ISSUE THREAD

**Issue by ShadowCube264** [Alexthw46/Ars-Elementals#1]
On version 1.18.1-0.3.0.1, the game crashed as soon as I cast a homing (fire) spell, without too many glyphs installed
Log:
[latest.log](https://github.com/Alexthw46/Ars-Elemental/files/8356129/latest.log)

**Comment by Alexthw46** [comment]
Dang, i added a line after the tests to optimize but i forgot a check to avoid that. I'll upload the fix asap

**Comment by ShadowCube264** [comment]
Awesome, thanks for the quick reply and fix!
