### ISSUE TITLE
[1.18.2] Mod causes cascading Render Thread Errors with Ars Noveau v2.80.

### ISSUE THREAD

**Issue by Hahahavana** [Alexthw46/Ars-Elementals#11]
Title says it all. Presumably this has something to do with the new implementation of Gekolib shading on that version. Downgrading to 2.79 fixes the crash.

**Comment by Alexthw46** [comment]
double of #10 and kinda also of #9 
already fixed in-dev but a side error came up with backporting strider & dolphin summons so it might take a bit
