### ISSUE TITLE
[1.19.2] Ars Elemental's Spore Blossom (ground) does not check for solid ground when placing

### ISSUE THREAD

**Issue by TelepathicGrunt** [Alexthw46/Ars-Elementals#13]
Forge: Ars Elemental 1.19.2-0.5.5.6

The vanilla Spore Blossom can only be placed on solid surfaces above it but it looks like Ars Elemental's Spore Blossom can be placed on anything as long as there's any block below. Which leads to strange stacking behavior such as below pic. Making the canSurvive to only return true if the below block's face is a full block would solve this. 
![image](https://user-images.githubusercontent.com/40846040/202903552-bfdd6e12-fb26-4071-97f9-2884249a6fb0.png)
![image](https://user-images.githubusercontent.com/40846040/202903705-1b0c1ad4-9f2f-46b4-9450-6de0ea930eed.png)

**Comment by Alexthw46** [comment]
i had issues with the method used by the vanilla blossom so it was disabled recently, with the face sturdy check is seems to behave as intended.
https://www.curseforge.com/minecraft/mc-mods/ars-elemental/files/4104849
