### ISSUE TITLE
Target/Agro glyph

### ISSUE THREAD

**Issue by shoverno2** [Alexthw46/Ars-Elementals#19]
I tested charm and found a little problem...
Spell damage doesn't apply agro to charmed entities.
Target sets only on weapon hit.
(melee[Hand, sword], ranged[bow])

So...
Then what about target spell..?
Just to make summons and charmed entities attack exact target.

**Comment by Alexthw46** [comment]
It's actually an issue for Ars itself, since apparently spell damage don't mark the target as attacked by the shooter correctly. That's not an exclusive of charmed mobs, wolves and other summons won't aggro with just spell damage.

Will have to fix that upstream too.

**Comment by Alexthw46** [comment]
As for summon targeting command, something will come in the near future in base Ars, so i'm closing this
