### ISSUE TITLE
Error building entry ars_elemental:armor/armor_aqua + Game crashing upon joining a server

### ISSUE THREAD

**Issue by Pokenar** [Alexthw46/Ars-Elementals#22]
I am posting this on a friend's behalf, they are having an issue where they are crashing during the join process of a server

For what it is worth, I am able to join fine, I also already instructed him to set the ram to the same amount I have, I also instructed him to delete the pack and redownload.

[latest (2).log](https://github.com/AllTheMods/ATM-8/files/10781765/latest.2.log)

The pack is All the Mods 8

**Comment by Alexthw46** [comment]
The only thing I can think of is that the friend and the server have two different versions of elemental. The crash happen on syncing the patchouli book, and a page format was changed in the latest update

**Comment by Pokenar** [comment]
Hm, we both have version 1.19.2-0.5.8.0, so if that was the case I should be crashing too.

If there's no other possible solution, I'll see about giving them my config files or something to see if curseforge is having an issue deleting their old stuff, even though I made sure the pack was deleted entirely and had them do a fresh install

**Comment by Alexthw46** [comment]
Well, it's weird that happen. I can put a guard to at least not crash at that point.
https://www.curseforge.com/minecraft/mc-mods/ars-elemental/files/4404112

**Comment by Pokenar** [comment]
Thank you, I'll get everyone to update to it and I'll let you know how it goes, though that may be a bit.

**Comment by Alexthw46** [comment]
It's a very minimal fix, so only the ones that had the problem need to update. The old version and this one should work together without issues

**Comment by Pokenar** [comment]
Well, your mod no longer shows in the log, but they still crash, I'll assume something else is the issue now.

**Comment by Alexthw46** [comment]
If it's really tied to something Ars, it could be a combination of the cpu/gpu architecture and the clash of the new sky shader for the block with Rubidium.
We would have an idea on how to fix it in that case, but we'll probably release an update with the config to toggle the skyblock rendering off to test

**Comment by Alexthw46** [comment]
For anyone stubling in the Error building entry ars_elemental:armor/armor_aqua, please check that your server and client versions of the mods are the same as first thing, a lot of other people found out later that the server still had pre 0.5.8. The crash is either related to the issue linked above by derekpowa (which is something weird client related and depending on hardware) or some kind of other mismatch

**Comment by Pokenar** [comment]
Had the server owner update to the new version just to make sure we weren't running an outdated version, and they crashed as well

We are both running Intel/Nvidia, particularly I have an i7-12700 with a 3060, while they have an i7-12700kf with a 3070
