### ISSUE TITLE
[1.19.2] Aethermancer Set Bonus Doesn't Reduce Fall Damage

### ISSUE THREAD

**Issue by Bomb-Bard** [Alexthw46/Ars-Elementals#38]
The Aethermancer set (Hat, Robes, Leggings, and Boots) does not reduce fall damage whatsoever.

To reproduce:
Start a world (with cheats, to get the set faster).
Without wearing the set, fall from 8 blocks. You will lose two and a half hearts (5 damage).
While wearing the set, fall from 8 blocks. You will lose two and a half hearts (5 damage).

Intended behavior:
When falling with the Aethermancer Set equipped, fall damage should be "highly reduced".

**Comment by Alexthw46** [comment]
Looks like a check added in the latest update cancel the damage tweaking when the damage is dealt by something not entity-related. Good catch, i'll try to release the hotfix today

**Comment by Alexthw46** [comment]
Please try out the new update and let me know if the issue can be closed

**Comment by Bomb-Bard** [comment]
The set now correctly reduces fall damage - thank you!
