### ISSUE TITLE
Flarecannon dead body stuck 

### ISSUE THREAD

**Issue by axozz** [Alexthw46/Ars-Elementals#39]
I spawnt a flarecannon and it walked onto a stonecutter and died. After that the dead body floating on that same location and will not despawn. Not even after a server restart. (With /kill @e[type=ars_elemental:firecannon_entity i cant delete the "dead body" of the firecannon. ) What can i do?

https://prnt.sc/zQT88bDhobfH (Screenshot)

**Comment by Alexthw46** [comment]
Oh, sorry for late response, didn't saw this.
Well, while i need to fix the kill command not working, you can simply use dispel to remove it (charm drops) or a magma cream to resurrect it. There is also a config option to disable this behavior.
