### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by kirito309** [Alexthw46/Ars-Elementals#43]
For some odd reason when ever i try loading mc with the 1.20.1 version of the mod im getting an error that says java.lang.reflect.InvocationTargetException: null for the mod, is there anyone that can assist me with this problem

**Comment by Alexthw46** [comment]
Which versions are you using? I suggest checking if you are on latest Ars Nouveau and Elemental since there were important changes in Nouveau recently. 
If the problem persist with the latest, post the crash log since that error alone says too little

**Comment by kirito309** [comment]
> Reference
Ah, the issue is resolved; looks like my Ars Nouveau was out of date. Thank u vm for the advice
