### ISSUE TITLE
Crash When Trying to Bypass Fire Resist?

### ISSUE THREAD

**Issue by ChosenArchitect** [Alexthw46/Ars-Elementals#44]
**Issue**:
So this is sort of a strange issue and I don't know if I'm reading this log correctly but we did have this crash happen on our server.
Seems someone tried to use an ignite spell on a mob in the nether and it caused this crash.

**Crash Log**:
https://pastebin.com/JKNyWTVe

**Mod Version**:
ars_elemental-1.20.1-0.6.2.1
ars_nouveau-1.20.1-4.7.1-all

**Comment by Alexthw46** [comment]
Oh damn, can't believe i let such an obvious loop slide. I know what's up.

**Comment by Alexthw46** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ars-elemental/files/4797915 should be solved by this
