### ISSUE TITLE
Ars Elemental form glyphs are not displayed properly

### ISSUE THREAD

**Issue by bastrian** [Alexthw46/Ars-Elementals#45]
Issue:
Ars Elemental form glyphs are not displayed properly and are referred to as ars_elemental_form_glyph inside the spellbook

Debug Log and latest Log does not show any Warning or Error.

Version used: MC 1.20.1 Mod Version 0.6.2.3

It might be a missing translation?

![ars](https://github.com/Alexthw46/Ars-Elemental/assets/1041566/f6542f52-d97e-4db9-b429-2ef1b1967c97)

For myself (tracking): JIRA Issue CC-5

**Comment by Alexthw46** [comment]
Is it only the Arc one? i changed the name recently so i probably forgot to update that translation key

**Comment by Alexthw46** [comment]
Uploaded a new file with the same name with the lang fixed
