### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by K6ZXS** [Alexthw46/Ars-Elementals#49]
mod failed to load correctly 
java.lang.NoClassDefFoundError: com/hollingsworth/arsnouveau/common/spell/augment/AugmentRandomize

[crash-2024-01-20_16.59.58-fml.txt](https://github.com/Alexthw46/Ars-Elemental/files/13997378/crash-2024-01-20_16.59.58-fml.txt)

**Comment by Alexthw46** [comment]
Update Ars Nouveau, latest for 1.19 is   . 22 and you have  .19.
Randomize was added with v. 20
