### ISSUE TITLE
Getting a render crash blaming Wizards Reborn when Ars Elemental is also installed

### ISSUE THREAD

**Issue by Arkiln** [Alexthw46/Ars-Elementals#50]
See https://github.com/MaxBogomol/WizardsReborn/issues/7

Removing Ars Elemental fixes the problem.

Initial modpack is https://www.curseforge.com/minecraft/modpacks/medieval-mc-mmc4

**Comment by Alexthw46** [comment]
There's no hint on why removing my mod does not crash, could even be a random crash caused by something else for all I know. The only things mentioned in the log are an error from WR mixins and an error with shields (and I don't add shields). Wait for a response from that mod author
