### ISSUE TITLE
[Bug] >> Crush Recipes has Invalid tags

### ISSUE THREAD

**Issue by KakashoLin** [Alexthw46/Ars-Elementals#55]
For this recipe
{
  "type": "ars_nouveau:crush",
  "input": {
    "tag": "minecraft:quartz_block"
  },
  "output": [
    {
      "chance": 1.0,
      "count": 3,
      "item": "minecraft:nether_quartz"
    },
    {
      "chance": 0.5,
      "count": 1,
      "item": "minecraft:nether_quartz"
    }
  ]
}

Tag needs to be changed to item, because it generates a barrier block.

**minecraft:nether_quartz** also needs to be **minecraft:quartz**

Minecraft: 1.20.1
Mod Version:  1.20.1.6.4.1

**Comment by Alexthw46** [comment]
i'll remove it entirely, the recipe is now inside base ars
