### ISSUE TITLE
java.lang.NoClassDefFoundError: com/hollingsworth/arsnouveau/common/potions/ParticleMobEffect

### ISSUE THREAD

**Issue by romogomor** [Alexthw46/Ars-Elementals#57]
Since I updated the mod today, I cannot start my Chosen's Modded Adventure because of the attached error.

I note that there is no ParticleMobEffect over at https://github.com/baileyholl/Ars-Nouveau/tree/main/src/main/java/com/hollingsworth/arsnouveau/common/potions but I'm not proficient enough with the javas to work out if yet another mod should be providing this class, sorry.

[crash-2024-04-13_11.28.17-fml.txt](https://github.com/Alexthw46/Ars-Elemental/files/14967173/crash-2024-04-13_11.28.17-fml.txt)

**Comment by Alexthw46** [comment]
You need to use Ars 4.10 minimum, you're on 4.9

**Comment by romogomor** [comment]
Thanks for the quick reply! And yes, Prism Launcher wasn't detecting that needed updating, thanks!
