### ISSUE TITLE
Crash when reloading resources

### ISSUE THREAD

**Issue by ozokuz** [Alexthw46/Ars-Elementals#6]
Game crashed when reloading resources in a singleplayer world

Minecraft Version: 1.18.2
Mod Version 0.4.9
Forge Version: 40.1.41

Crash Report:

https://gist.github.com/ozokuz/72cedaa20ad1e447bfe117107ff0a465

**Comment by Alexthw46** [comment]
I kinda noticed that too, not sure why curios do it but i''ve added a guard against it. I'm updating soon for these little adjustments

**Comment by Alexthw46** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-elemental-elemental-spell-foci/files/3832026
Fixing it, also reported to curios just to be sure
