### ISSUE TITLE
Dedicated Server only crash with Deeper and Darker 

### ISSUE THREAD

**Issue by cr0ss0vr** [Alexthw46/Ars-Elementals#65]
When taking damage when wearing Pyromancer or Aquamancer gear (T4 armour), when Deeper and Darker is installed, the server instantly crashes. 

When the Forge settings "removeErroringBlockEntities" and "removeErroringEntities" are set to 'true', all damage sources disappear (arrows, zombies, etc.)

"java.lang.AbstractMethodError: Receiver class alexthw.ars_elemental.common.items.armor.AAMaterials$ModdedArmorMaterial does not define or inherit an implementation of the resolved method 'abstract java.lang.String m_6082_()' of interface net.minecraft.world.item.ArmorMaterial.
	at com.kyanite.deeperdarker.DeeperDarkerEvents.lambda$livingDamageEvent$2(DeeperDarkerEvents.java:143) ~[deeperdarker-forge-1.20.1-1.3.0.jar%23475!/:1.3.0] {re:classloading}..."

Attached are some server crash logs.
[crash-2024-09-06_14.58.54-server.txt](https://github.com/user-attachments/files/16909025/crash-2024-09-06_14.58.54-server.txt)
[crash-2024-09-06_13.39.33-server.txt](https://github.com/user-attachments/files/16909032/crash-2024-09-06_13.39.33-server.txt)
[crash-2024-09-06_13.59.19-server.txt](https://github.com/user-attachments/files/16909033/crash-2024-09-06_13.59.19-server.txt)

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/5698212

see changelog
