### ISSUE TITLE
[1.21.1] Crash on startup with ars 5.2.0

### ISSUE THREAD

**Issue by CubeTwo** [Alexthw46/Ars-Elementals#68]
Crash on startup with ars 5.2.0

NeoForge 21.1.69
ars_nouveau-1.21.1-5.2.0-all
ars_elemental-1.21.0-0.7.0.5
![Screenshot from 2024-10-20 18-31-05](https://github.com/user-attachments/assets/9a1b2274-2aa6-40eb-93c3-358e01fadfcb)
crashlog:
[crash-2024-10-20_18.31.07-client.txt](https://github.com/user-attachments/files/17450901/crash-2024-10-20_18.31.07-client.txt)

**Comment by Alexthw46** [comment]
Jeez, it was just uploaded and Bailey hasn't announced it yet. The version on maven should work on it but haven't had time to check if it's all ready for releasing the update.

**Comment by CubeTwo** [comment]
> Jeez, it was just uploaded and Bailey hasn't announced it yet. The version on maven should work on it but haven't had time to check if it's all ready for releasing the update.

oh, sorry, just coincidence, i updated mods in wrong time. I just wait normal update.
tried  maven version its blame not_enough_glyphs now, not_enough_glyphs1.21.0-4.0.0.5.4.jar from maven dont work too.
![image](https://github.com/user-attachments/assets/19cdde65-69d8-4002-b081-515ba95ac4bc)

**Comment by Alexthw46** [comment]
Ah, that must be due to how the maven makes the files, it's a very recent change. I could have missed that one, thanks. Neg is up for an update too anyway
