### ISSUE TITLE
Cannot grow flashpine

### ISSUE THREAD

**Issue by uhloin** [Alexthw46/Ars-Elementals#71]
MC 1.21.1
Tried to grow flashing trees from saplings (with Grow spell), and mine it (Fell spell) but after 10 trees there are no even single flashpine.

**Comment by Alexthw46** [comment]
Arch fruits never dropped that way. They're like cocoa beans. This is how they work in base mod, not my rules

**Comment by uhloin** [comment]
tried vexing tree, you're right
