### ISSUE TITLE
[1.21.1] Cannot put Soulbound enchant to Iron's spell spellbooks

### ISSUE THREAD

**Issue by CubeTwo** [Alexthw46/Ars-Elementals#73]
Cannot put Soulbound enchant to Iron's spell spellbooks, all other curios items can have soulbound enchant.

![2024-10-29_13 50 03](https://github.com/user-attachments/assets/c1b9d6f5-4bea-4878-acd3-50f7e21fbae8)
![2024-10-29_13 50 05](https://github.com/user-attachments/assets/d5d0aafe-a4dd-436d-a4af-d02210364cea)
![2024-10-29_14 10 36](https://github.com/user-attachments/assets/06c804e7-a8fc-4319-8b7b-93171ddf8682)
![2024-10-29_14 10 40](https://github.com/user-attachments/assets/d62dac20-2665-490b-bc88-578c2159f4c1)

Neoforge 21.1.72
ars_nouveau-1.21.1-5.2.2-all
ars_elemental-1.21.1-0.7.0.8

**Comment by Alexthw46** [comment]
In 1.21 the criteria for enchantments compatibility is tag based, i could sneak in the curio tag they use i guess
