### ISSUE TITLE
Add missing Thread Tied on Elemental Armor 

### ISSUE THREAD

**Issue by ffuentesm** [Alexthw46/Ars-Elementals#8]
Here we have two armors with the Tier 2 
![image](https://user-images.githubusercontent.com/44974827/194740368-b7f4ac2e-0924-4856-9530-c203e8d2278a.png) 
![image](https://user-images.githubusercontent.com/44974827/194740396-b82b89cc-89f6-42ca-ad0e-35f55ae28c70.png)
As you can see, only the Base Ars armor has the Tier tag on the description.

**Comment by Alexthw46** [comment]
Elemental armors are always of tier3. They can be crafted from any tier of the corresponding arcanist piece, so displaying a tier that is always the same would be pretty useless, they can't be upgraded further.

**Comment by ffuentesm** [comment]
Would have been nice to know that before. 
Even if "useless" it would keep the consistency of things. 
Also, would be nice to block the "armor upgrade" from working on the Elemental armor. Because the Armor upgrade crafting still accepts the elemental armor even though they are already maxed out.

**Comment by ffuentesm** [comment]
Actually no, I was able to Upgrade the Geomancer's set to Tier 2
![image](https://user-images.githubusercontent.com/44974827/194778223-cce9e0d0-ce0d-4cd3-9afe-91b61fc6d5b5.png)
![image](https://user-images.githubusercontent.com/44974827/194778239-0cac5c66-9462-4ca3-b78d-ed20fe9c94d6.png)
So that is making me confused

**Comment by Alexthw46** [comment]
Apparently the armor needs to be equipped at least once for the tier to update to 3. I'll try moving the check to the inventory tick instead of the equipped and probably lock the elemental upgrade to tier3 armors so they don't risk remaining in the fake tier 1 stage.
